Support building with GHC 8.10 with a sprinkle of language extensions
GHC 8.10 is somewhat pickier about needing to enable the `GADTs` language
extension than in previous versions of GHC. (See
[this section](https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/8.10#ghc-is-pickier-about-requiring-language-extensions-to-match-on-gadt-constructors)
of the 8.10 Migration Guide for the full story.) As a result, `GADTs` needs
to be enabled in a handful of modules in order to make `saw-script` compile
with 8.10.

In addition, I enabled `NoMonoLocalBinds` in `Crucible.JVM.BuiltinsJVM`. This
is because `MonoLocalBinds` (which `GADTs` automatically enables) causes some
local definitions in that module to fail to typecheck:

```
[69 of 71] Compiling SAWScript.Crucible.JVM.BuiltinsJVM ( src/SAWScript/Crucible/JVM/BuiltinsJVM.hs, interpreted )

src/SAWScript/Crucible/JVM/BuiltinsJVM.hs:181:47: error:
    • Couldn't match type ‘Term’ with ‘Cryptol.Type’
      Expected type: W4.SymExpr
                       (CrucibleSAW.SAWCoreBackend
                          Nonce.GlobalNonceGenerator
                          Yices.Connection
                          (W4.Flags 'What4.Expr.Builder.FloatReal))
                       bt
                     -> IO Cryptol.Type
        Actual type: W4.Expr Nonce.GlobalNonceGenerator bt -> IO Term
    • In the second argument of ‘Crucible.asSymExpr’, namely
        ‘(CrucibleSAW.toSC sym)’
      In a stmt of a 'do' block:
        t <- Crucible.asSymExpr regval (CrucibleSAW.toSC sym) failure
      In the expression:
        do gp <- getGlobalPair opts pr
           let regval = gp ^. Crucible.gpValue
           let regty = Crucible.regType regval
           let failure = fail $ unwords ...
           ....
    |
181 |               t <- Crucible.asSymExpr regval (CrucibleSAW.toSC sym) failure
    |                                               ^^^^^^^^^^^^^^^^^^^^

src/SAWScript/Crucible/JVM/BuiltinsJVM.hs:189:54: error:
    • Couldn't match expected type ‘Term’
                  with actual type ‘Cryptol.Type’
    • In the second argument of ‘TypedTerm’, namely ‘t’
      In the expression: TypedTerm (Cryptol.tMono cty) t
      In an equation for ‘tt’: tt = TypedTerm (Cryptol.tMono cty) t
    |
189 |               let tt = TypedTerm (Cryptol.tMono cty) t
    |                                                      ^
```

I opted for the simplest approach (disabling `MonoLocalBinds`) here to fix the
issue.